### ISSUE TITLE
不使用plum安装 rime-emoji 非官方教程

### ISSUE THREAD

**Issue by Sciroccogti** [rime/rime-emoji#16]
这个repo似乎没有[wiki](https://github.com/rime/rime-emoji/wiki)，故权且在这里记一笔，兴许能帮到一两个人。

我没有安装[東風破](https://github.com/rime/plum)，而是使用比较简单的小狼毫自带的管理界面。

1.  下载[本repo压缩包](https://github.com/rime/rime-emoji/archive/master.zip)，假设下载路径为`D:\Download\rime-emoji-master.zip`

2.  右键图标，进入 *方案選單設定*

![image](https://user-images.githubusercontent.com/32357397/68539496-fc045280-03bf-11ea-91b1-96ddccadbcd3.png)

3. 点击左下角 *獲取更多輸入方案*

![image](https://user-images.githubusercontent.com/32357397/68539568-ea6f7a80-03c0-11ea-9a7d-ac08904c6b97.png)

4.  进入shell，输入下载的压缩包路径，譬如`D:\Download\rime-emoji-master.zip`

![image](https://user-images.githubusercontent.com/32357397/68539643-71bcee00-03c1-11ea-9d24-b691f4f44f65.png)

5.  打开 *用戶文件夾* 中的`emoji_suggestion.yaml`，将其中的内容复制到想要添加emoji输入的输入法自定义文件中。以`luna_pinyin_simp.custom.yaml`为例，复制完成的效果如下：

```yaml
patch:
  punctuator/full_shape:
    "\\" : "、"
  #以上是本人自定义部分，与本repo无关

  switches/@next:
    name: emoji_suggestion
    reset: 1
    states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
  'engine/filters/@before 0':
    simplifier@emoji_suggestion
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    tips: all
```

5. 重新部署

此时，如果不出意外，你应该能在正常输入时看到emoji候选。

![image](https://user-images.githubusercontent.com/32357397/68539684-37078580-03c2-11ea-8cec-6059872bbdd1.png)
