### ISSUE TITLE
自助安装之后还是没有反应

### ISSUE THREAD

**Issue by liuqin19980818** [rime/rime-emoji#18]
```yaml

# luna_pinyin_simp.custom.yaml
patch:
# 指定自定义词库位置
  "translator/dictionary": luna_pinyin.my
# 标点符号全英文
  "punctuator/import_preset": alternative
# emoji的使用
  switches/@next:
      name: emoji_suggestion
      reset: 1
      states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
    'engine/filters/@before 0':
      simplifier@emoji_suggestion
    emoji_suggestion:
      opencc_config: emoji.json
      option_name: emoji_suggestion
      tips: all


```

另外的文件都复制过来了，opencc的也是，但是还是一样，切换的时候找不到这个emoji_suggestion
