### ISSUE TITLE
可以用代码打出emoji吗

### ISSUE THREAD

**Issue by edr1412** [rime/rime-emoji#23]
比如github的解析这样`:joy:`打出:joy:
官方提供的文件把中文映射emoji了，我个人觉得用英文稍微方便点
还有 fcitx的码表好像在rime不管用耶

**Comment by LEOYoon-Tsaw** [comment]
等你做了唄，emoji的官方英文在unicode裏有

**Comment by lotem** [comment]
用 https://github.com/rime/rime-emoji/tree/schema 分支上的輸入方案可以輸入代碼

**Comment by edr1412** [comment]
> 用 https://github.com/rime/rime-emoji/tree/schema 分支上的輸入方案可以輸入代碼

这个好像是别人自己定义的吧，虽然也挺方便的
大概是要这种标准吧 https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md

Linux上的fcitx其实是自带emoji的快速输入码表啦，rime上要是能用就好了

**Comment by lotem** [comment]
Rime沒有內置碼表，都要自己定義的。樓主可以多嘗試做幾種。

**Comment by Ynjxsjmh** [comment]
schema 分支分支下有两个文件 `emoji.dict.yaml` 和 `emoji.schema.yaml`，如果像下面这样 patch 到 `<輸入方案標識>.schema.yaml` 里面的话，用 =`= 就可以直接搜索 emoji 了

```yaml
patch:
  schema/dependencies:
    - emoji
  recognizer/patterns/reverse_lookup: "`[a-z]*$"
  reverse_lookup:
    dictionary: emoji
    enable_completion: false
    prefix: "`"
    tips: 〔emoji〕
```

但是和 emoji 类似，我还有两个文件 `kaomoji.dict.yaml` 和 `kaomoji.schema.yaml` 用于配置颜文字，用类似的配置也可以只查颜文字

```yaml
patch:
  schema/dependencies:
    - kaomoji
  recognizer/patterns/reverse_lookup: "`[a-z]*$"
  reverse_lookup:
    dictionary: kaomoji
    enable_completion: false
    prefix: "`"
    tips: 〔颜文字〕
```

有没有一种配置方法可以配置两个 prefix，一个 prefix 用以查 emoji，另一个 prefix 查颜文字呢？
