### ISSUE TITLE
Emoji 表情能不能固定在每一行的最后一个候选词吗

### ISSUE THREAD

**Issue by ililu2000** [rime/rime-emoji#24]
比如我打 fan 字，第一行候选词出来的是各种各样 Emoji 饭，很影响打字效率
<img width="564" alt="截屏2021-02-12 下午6 38 25" src="https://user-images.githubusercontent.com/78154435/107760216-5d099b80-6d64-11eb-8a03-68e37dd20d32.png">
如果把所有 Emoji 都固定在 第9个候选词，或者所有 emoji 都固定在每一行后三个候选词上，这样就可以在不影响效率的前提下还能用 Emoji

**Comment by LEOYoon-Tsaw** [comment]
不能。
可以試試tips: none，寫在emoji的simplifier下

**Comment by tkuwill** [comment]
樓主通常可能是**有時候打個字時，臨時想用emoji來表達**，**平時工作或學習時是用不到的**。個人建議這樣設定（我使用地球拼音，放在`terra_pinyin.custom.yaml`）：
```yaml
patch:
  switches/@next:
    name: emoji_suggestion
    reset: 0 # 0 則為預設關閉，需從<C-`>設定選單中開啓。
    states: [ "🈚︎", "🈶️" ]
  'engine/filters/@before 0':
    simplifier@emoji_suggestion
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    tips: none
    inherit_comment: false

```
如此一來，**預設打字時emoji就不會出現在候選字中**，當需要打emoji時，在使用`<C-`>`來進行切換。重點就是`reset: 0 `。@ililu2000
