### ISSUE TITLE
命令或自助安裝均無效

### ISSUE THREAD

**Issue by cakvfcwz** [rime/rime-emoji#35]
使用命令安裝在custom檔內增加了

```
__patch:
# Rx: emoji:customize:schema {
  - patch/+:
      __include: emoji_suggestion:/patch
# }
```
經test無效
之後又註釋掉這一段，通過手動安裝將schema檔修改成了

```
switches:
  ...
  - name: emoji_suggestion
    reset: 1
    states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
...
engine:
  ...
  filters:
    - simplifier@emoji_suggestion
    - simplifier
    - uniquifier
...
emoji_suggestion:
  option_name: emoji_suggestion
  opencc_config: emoji.json
  tips: all
```

opencc內的文件也都複製了，但方案中只有switches這裏有效，無法打出任何emoji
schema是內置的基於朙月拼音的自然碼雙拼
