### ISSUE TITLE
How to set keybinding to toggle emoji suggestions?

### ISSUE THREAD

**Issue by sierxue** [rime/rime-emoji#44]
I'm using ibus-rime on ubuntu 20.04, which was installed by compiling source.

I've installed emoji with plum, and it works smoothly. I greatly appreciate it!

Now I have set the default option as "0", then the emoji suggestions does not show as I expect. I want to set up a shortcut to change the option to "1", and have setup in the schema:

``` 
patch:
  'key_binder/bindings': # This does not work as I expect?
     - { when: always, accept: Control+Shift+9, toggle: emoji_suggestion }
     - { when: always, accept: Control+Shift+(, toggle: emoji_suggestion }
```

However, it does not work, and I cannot see emoji suggestions.

**Comment by LEOYoon-Tsaw** [comment]
You will need to set `option_name` in the emoji conversion setup, such as:

```yaml
emoji_conversion:
  opencc_config: emoji.json
  option_name: show_emoji
  tags: [ pinyin, jyutping, abc ]
  tips: none
  inherit_comment: false
```

Then use this name to bind to binding

```yaml
key_binder:
  import_preset: default
  bindings:
    - { when: always, accept: Control+6, toggle: show_emoji }
```
