### ISSUE TITLE
自助安装emoji缺少文档示例

### ISSUE THREAD

**Issue by iwoomi** [rime/rime-emoji#57]
希望这个自已添加的方法能给出一个实际的配置文件例子，这样新手也知道该怎么配置，毕竟有时候全部输入法方案都已经安装了，就不会去用自动安装的方法了，有实际的示例文件方便新手参考

<img width="640" alt="Image" src="https://github.com/user-attachments/assets/e7a79bb1-077c-43a2-bf74-1063dc078f3b" />

**Comment by LEOYoon-Tsaw** [comment]
配置內容就在emoji_suggestion.yaml裡面

**Comment by BenSYZ** [comment]
例如：我用的是 `lunar_pinyin`，配置文件在 ` ~/.local/share/fcitx5/rime/luna_pinyin.custom.yaml`，参考 `emoji_sugguestion.yaml`，将对应的 patch 下的节贴上去就好，我的就是这样

```yaml
patch:
  engine:
    filters:
      - simplifier
      - uniquifier
    processors:
      - ...
    segmentors:
      - ...
    translators:
      - ...
  switches:
    - ...

  switches/@next:
    name: emoji_suggestion
    reset: 1
    states: [ "🈚︎", "🈶️" ]
  'engine/filters/@before 0':
    simplifier@emoji_suggestion
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    tips: none
    inherit_comment: false

  translator/dictionary: luna_pinyin.list

  'speller/algebra':
    - ...
...
```
